# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.ForeignKey(default=1565747328, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TypesOfDishes'),
        ),
    ]
