# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20171113_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typesofdishes',
            old_name='type',
            new_name='name',
        ),
        migrations.AddField(
            model_name='typesofdishes',
            name='description',
            field=models.CharField(blank=True, help_text='max_length=256', max_length=256),
        ),
        migrations.AddField(
            model_name='typesofdishes',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='base/type_dish_img/'),
        ),
    ]
