# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20171113_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishimg',
            old_name='is_activ',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='typesofdishes',
            old_name='is_activ',
            new_name='is_active',
        ),
    ]
