# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20171114_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
