# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20171114_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
