# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(help_text='max_length=256', max_length=256)),
                ('text', models.CharField(help_text='max_length=1024', max_length=1024)),
                ('img', models.ImageField(upload_to='news/')),
                ('is_activ', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
